---
title: "scRNAseq"
output: html_notebook
---

```{r}
library(tidyverse)
library(Seurat)
library(ggthemes)
library(patchwork)
```

```{r}
pbmc.data <- Read10X(data.dir='filtered_gene_bc_matrices/hg19/')
pbmc <- CreateSeuratObject(counts = pbmc.data, project='pbmc3k', min.cells=3, min.features=200)
pbmc
```

### Pre-processing

```{r}
# Percent mitochondrial genes
pbmc[['percent.mt']] <- PercentageFeatureSet(pbmc, pattern='^MT-')
```

```{r}
VlnPlot(pbmc, features = c('nFeature_RNA', 'nCount_RNA', 'percent.mt'), ncol=3)
```

```{r}
plot1 <- FeatureScatter(pbmc, feature1= 'nCount_RNA', feature2 = 'percent.mt')
plot2 <- FeatureScatter(pbmc, feature1= 'nCount_RNA', feature2 = 'nFeature_RNA')
plot1 + plot2
```

```{r}
pbmc <- subset(pbmc, subset=nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
```


### Data normalization
```{r}
pbmc <- NormalizeData(pbmc, normalization.method = 'LogNormalize', scale.factor = 10000)
```

### Feature selection

```{r}
pbmc <- FindVariableFeatures(pbmc, selection.method = 'vst', nfeatures = 2000)
top2000 <- VariableFeatures(pbmc)

```

```{r}
mat <- GetAssayData(pbmc, slot='counts')
mats <- as.matrix(mat[apply(mat, 1, function(x) sum(x>0) > 10), ])
mats <- mats[rownames(mats) %in% top2000, ]
mats <- mats[!grepl('^RP', rownames(mats)), ]
mats <- mats[!grepl('^MT-', rownames(mats)), ]
write.csv(as.matrix(mats), 'data_filtered.csv', quote=F)
```







